name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history for analysis

      # Run SonarQube scan
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Optionally fail job if Quality Gate fails
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Install Trivy
      - name: Install Trivy
        run: |
          # Install dependencies for Trivy
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release

          # Add Trivy repository key and source list
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list

          # Install Trivy
          sudo apt-get update
          sudo apt-get install -y trivy

      # Scan the repository with Trivy
      - name: Run Trivy Scan
        run: |
          # Run Trivy to scan for vulnerabilities in the filesystem
          trivy fs .
